name: "Circuit-level noise setup"
description: "Setup for a circuit-level noise model that can be used for any distance."

error_prob: &prob "prob"
add_assign_error: &flag "add_assign_error"

setup:
  - sq_error_prob: *prob
    cz_error_prob: *prob
    meas_error_prob: *prob
    reset_error_prob: *prob
    idle_error_prob: *prob
    assign_error_flag: *flag
    assign_error_prob: *prob
