name: "Circuit-level noise based on experiment parameters"
description: "Setup for a circuit-level noise model based on the calibration of the Aurelius device."

setup:
  - qubit: D1
    freq: 4900
    relax_time: 13973
    deph_time: 7181
    gate_error: 0.0011
    assign_error: 0.0281
    qnd_error: 0
    res_exc_error: 0
  - qubit: D2
    freq: 4900
    relax_time: 14460
    deph_time: 12197
    gate_error: 0.0016
    assign_error: 0.1182
    qnd_error: 0
    res_exc_error: 0
  - qubit: D3
    freq: 4900
    relax_time: 10244
    deph_time: 15769
    gate_error: 0.0061
    assign_error: 0.0275
    qnd_error: 0
    res_exc_error: 0
  - qubit: D5
    freq: 6700
    relax_time: 11508
    deph_time: 10684
    gate_error: 0.0009
    assign_error: 0.0135
    qnd_error: 0
    res_exc_error: 0
  - qubit: D6
    freq: 6700
    relax_time: 5858
    deph_time: 9737
    gate_error: 0.0033
    assign_error: 0.0216
    qnd_error: 0
    res_exc_error: 0
  - qubit: D8
    freq: 4900
    relax_time: 11273
    deph_time: 14264
    gate_error: 0.0024
    assign_error: 0.0502
    qnd_error: 0
    res_exc_error: 0
  - qubit: D9
    freq: 4900
    relax_time: 18161
    deph_time: 14397
    gate_error: 0.0041
    assign_error: 0.0563
    qnd_error: 0
    res_exc_error: 0
  - qubit: X1
    freq: 6000
    relax_time: 9902
    deph_time: 6587
    gate_error: 0.0027
    assign_error: 0.031
    qnd_error: 0.0906
    res_exc_error: 0
  - qubit: X2
    freq: 6000
    relax_time: 12423
    deph_time: 13410
    gate_error: 0.0050
    assign_error: 0.0156
    qnd_error: 0.0914
    res_exc_error: 0
  - qubit: X3
    freq: 6000
    relax_time: 8717
    deph_time: 11483
    gate_error: 0.0032
    assign_error: 0.0182
    qnd_error: 0.0601
    res_exc_error: 0
  - qubit: X4
    freq: 6000
    relax_time: 7058
    deph_time: 11125
    gate_error: 0.0033
    assign_error: 0.0302
    qnd_error: 0.0349
    res_exc_error: 0
  - qubit: Z1
    freq: 6000
    relax_time: 5105
    deph_time: 4471
    gate_error: 0.0093
    assign_error: 0.0198
    qnd_error: 0.0533
    res_exc_error: 0
  - qubit: Z2
    freq: 6000
    relax_time: 10612
    deph_time: 18038
    gate_error: 0.0022
    assign_error: 0.0381
    qnd_error: 0.0383
    res_exc_error: 0

  - qubits: [X1, D1]
    gate_error: 0.0179
  - qubits: [X1, D2]
    gate_error: 0.0216

  - qubits: [X2, D2]
    gate_error: 0.0259
  - qubits: [X2, D3]
    gate_error: 0.0143

  - qubits: [Z2, D3]
    gate_error: 0.0124
  - qubits: [Z2, D6]
    gate_error: 0.0334

  - qubits: [Z1, D1]
    gate_error: 0.0270
  - qubits: [Z1, D5]
    gate_error: 0.0256

  - qubits: [X3, D5]
    gate_error: 0.0340
  - qubits: [X3, D8]
    gate_error: 0.0149

  - qubits: [X4, D8]
    gate_error: 0.0180
  - qubits: [X4, D9]
    gate_error: 0.0290

  - sq_gate_duration: 20
    cz_gate_duration: 40
    meas_duration: 800
